FROM php:5.4-fpm
# PHP 5.4.45 (cli) (built: Dec  5 2015 08:38:59) 
# Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
# Debian 8 (jessie)

# Debian 8 has been moved to archive
# RUN <<EOR
# cat << EOF > /etc/apt/sources.list
# deb http://archive.debian.org/debian jessie main
# deb http://archive.debian.org/debian-security jessie/updates main
# EOF
# EOR

# disable expired CA
RUN sed -i '/^mozilla\/DST_Root_CA_X3.crt$/ s/^/!/' /etc/ca-certificates.conf
RUN update-ca-certificates

RUN docker-php-ext-install pdo_mysql mysqli

# add xdebug
RUN pecl channel-update pecl.php.net && \
  pecl install xdebug-2.4.1 && \
  docker-php-ext-enable xdebug

ARG quickform_enabled
RUN test $quickform_enabled -eq 1 && pear install html_quickform || :

# # add dev user
# RUN groupadd -r dev && useradd -r -g dev dev
# RUN mkdir /home/dev
# RUN chown -R dev:dev /home/dev

COPY container_setup.sh /root/container_setup.sh

WORKDIR /work

ENTRYPOINT [ "bash", "/root/container_setup.sh" ]