version: '3'
services:
  php:
    build:
      context: .
      dockerfile: dockerfile.php-dev
    image: php-dev:0.3.4
    ports:
      - "2222:22" # wth: apparently yaml thinks this is a date?
    expose:
      - 9000
    volumes:
      - ./context:/mnt/context
      # - ./term_keys:/mnt/term_keys
      - ./container_setup.ps1:/root/container_setup.ps1
    environment:
      DEFAULT_GIT_USER: User Name
      DEFAULT_GIT_EMAIL: uname@org.com
      USER_ROOT_PWORD: test123
      # SSH_KEY_BITBUCKET: id_docker_php_bitbucket
      # SSH_KEY_TERM: id_docker_php_ssh_term
      # SSH_KEY_TERM_REGENERATE: 1

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./default.conf:/etc/nginx/conf.d/default.conf
  #     # - ./www:/usr/share/nginx/html

# volumes:
#   php-dev-context: