FROM php:5.4-fpm
# PHP 5.4.45 (cli) (built: Dec  5 2015 08:38:59) 
# Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
# Debian 8 (jessie)

RUN apt-get -y update && apt-get -y install \
  git \
  libicu52 \
  openssh-server

RUN curl -LJO https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-lts_7.2.6-1.deb_amd64.deb
RUN dpkg -i powershell-lts_7.2.6-1.deb_amd64.deb
RUN rm powershell-lts_7.2.6-1.deb_amd64.deb

RUN curl -sS https://starship.rs/install.sh | sh -s -- -y
RUN curl https://getmic.ro | bash
RUN mv micro /usr/bin

RUN docker-php-ext-install pdo_mysql mysqli
# RUN pear install html_quickform

# add xdebug
RUN pecl channel-update pecl.php.net && \
  pecl install xdebug-2.4.1 && \
  docker-php-ext-enable xdebug

# # add dev user
# RUN groupadd -r dev && useradd -r -g dev dev
# RUN mkdir /home/dev
# RUN chown -R dev:dev /home/dev

COPY container_setup.ps1 /root/container_setup.ps1

WORKDIR /work

ENTRYPOINT [ "pwsh", "-f", "/root/container_setup.ps1" , "-Startup" ]