FROM php:5.4-fpm
# PHP 5.4.45 (cli) (built: Dec  5 2015 08:38:59) 
# Copyright (c) 1997-2014 The PHP Group
# Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
# Debian 8 (jessie)

# FROM php:5.6-fpm-jessie

RUN curl -LJO https://github.com/PowerShell/PowerShell/releases/download/v7.2.6/powershell-lts_7.2.6-1.deb_amd64.deb

RUN apt-get -y update && apt-get -y install \
  git \
  libicu52 \
  openssh-server

RUN dpkg -i powershell-lts_7.2.6-1.deb_amd64.deb
RUN rm powershell-lts_7.2.6-1.deb_amd64.deb

#set shell things
RUN curl -sS https://starship.rs/install.sh | sh -s -- -y

WORKDIR /root
COPY php_docker_profile.ps1 .config/powershell/Microsoft.PowerShell_profile.ps1
COPY php_docker_bashrc.sh ./.bashrc
COPY container_setup.ps1 ./

# WORKDIR /work
# VOLUME [ "/mnt" ]
# ENTRYPOINT [ "pwsh" ]