FROM php:8.2-fpm-alpine3.21
# PHP 8.2.27 (cli) (built: Jan  8 2025 18:09:44) (NTS)
# Zend Engine v4.2.27, Copyright (c) Zend Technologies

RUN \
	# packages
	apk update && \
	apk add --no-cache \
	autoconf=2.72-r0 \
	build-base=0.5-r3 \
	linux-headers=6.6-r1 \
	neovim=0.10.2-r0 \
	nushell=0.100.0-r1 \
	postgresql17-dev=17.2-r0 \
	&& \
	# database extensions
	docker-php-ext-install pdo_mysql mysqli pdo_pgsql \
	&& \
	# xdebug
	pecl channel-update pecl.php.net && \
	pecl install xdebug-3.4.1 && \
	docker-php-ext-enable xdebug

# TODO:
# - [x] consider alpine
# - [ ] consider nushell
#   - [ ] cull the operations down to only the path manipulation

# COPY container_setup.ps1 /root/container_setup.ps1

WORKDIR /work

# ENTRYPOINT [ "nu", "/root/container_setup.nu" ]
