version: '3'
services:
  php55:
    build:
      # ulimits:
      #   nofile: 10000 # required if you wish to use apt-get
      context: .
      dockerfile: dockerfile.php-dev-55
      # args:
      #   quickform_enabled: 1
    image: php-dev:0.6.2-55
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2223:22"
    expose:
      - 9000
    volumes:
      - php-dev-context:/mnt/context
      # - ./context:/mnt/context
      # - ./php_ini:/mnt/php_ini # to receive original config
      # - ./container_setup.sh:/root/container_setup.sh
      # - ./php54.ini:/usr/local/etc/php/php.ini
      # - ./www:/var/www/html
      # - ./lib:/var/www/lib
    env_file: php_env

  php74:
    build:
      context: .
      dockerfile: dockerfile.php-dev-74
    image: php-dev:0.6.2-74
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2222:22"
    expose:
      - 9000
    volumes:
      - php-dev-context:/mnt/context
      # - ./context:/mnt/context
      # - ./term_keys:/mnt/term_keys
      # - ./php_ini:/mnt/php_ini
      # - ./container_setup.ps1:/root/container_setup.ps1
      # - ./php74.ini:/usr/local/etc/php/php.ini
      # - ./www:/var/www/html
      # - ./lib:/var/www/lib
    env_file: php_env

  nginx54:
    depends_on:
      - php54
    image: nginx:1.24-alpine
    ports:
      - 5054:80
    volumes:
      # - ./www:/usr/share/nginx/html
      # - ./js:/usr/share/nginx/html/global
      - ./nginx54.conf:/etc/nginx/conf.d/default.conf
  
  nginx74:
    depends_on:
      - php74
    image: nginx:1.24-alpine
    ports:
      - 5074:80
    volumes:
      # - ./www:/usr/share/nginx/html
      # - ./js:/usr/share/nginx/html/global
      - ./nginx74.conf:/etc/nginx/conf.d/default.conf

  my_db:
    build:
      context: .
      dockerfile: dockerfile.mariadb
    image: mydb-dev:0.4.0
    # image: mariadb
    volumes:
      - mydb:/var/lib/mysql
      - ./temp/my_sync_db:/temp/sync_db
      - ./sync_db.sh:/sync_db.sh
      # - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: poi098
      MARIADB_DATABASE: mydb
      MARIADB_USER: mydb
      MARIADB_PASSWORD: abc123

  pg_db:
    build:
      context: .
      dockerfile: dockerfile.postgres
    image: pgdb-dev:0.4.0
    # image: postgres:15 # PostgreSQL version: 15.5 (Debian 15.5-1.pgdg120+1) through PHP extension PgSQL
    # ports:
    #   - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
      # - ./pg15-postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./pg15-pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./temp/pg_sync_db:/temp/sync_db
      - ./sync_db.sh:/sync_db.sh
    environment:
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: abc123

  adminer:
    image: adminer
    ports: 
      - 8080:8080

volumes:
  php-dev-context:
  mydb:
  pgdb: