version: '3'
services:
  php54:
    build:
      context: .
      dockerfile: dockerfile.php-dev-54
    image: php-dev:0.5.3-54
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2223:22"
    expose:
      - 9000
    volumes:
      - php-dev-context:/mnt/context
      # - ./context:/mnt/context
      # - ./term_keys:/mnt/term_keys
      # - ./php_ini:/mnt/php_ini
      # - ./container_setup.ps1:/root/container_setup.ps1
      # - ./php54.ini:/usr/local/etc/php/php.ini
      # - ./www:/var/www/html
      # - ./lib:/var/www/lib
    env_file: php_env

  php74:
    build:
      context: .
      dockerfile: dockerfile.php-dev-74
    image: php-dev:0.5.3-74
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2222:22"
    expose:
      - 9000
    volumes:
      - php-dev-context:/mnt/context
      # - ./context:/mnt/context
      # - ./term_keys:/mnt/term_keys
      # - ./php_ini:/mnt/php_ini
      # - ./container_setup.ps1:/root/container_setup.ps1
      # - ./php74.ini:/usr/local/etc/php/php.ini
      # - ./www:/var/www/html
      # - ./lib:/var/www/lib
    env_file: php_env

  nginx54:
    image: nginx:alpine
    ports:
      - 5054:80
    volumes:
      # - ./www:/usr/share/nginx/html
      # - ./js:/usr/share/nginx/html/global
      - ./nginx54.conf:/etc/nginx/conf.d/default.conf
  
  nginx74:
    image: nginx:alpine
    ports:
      - 5074:80
    volumes:
      # - ./www:/usr/share/nginx/html
      # - ./js:/usr/share/nginx/html/global
      - ./nginx74.conf:/etc/nginx/conf.d/default.conf

  my_db:
    build:
      context: .
      dockerfile: dockerfile.mariadb
    image: mydb-dev:0.4.0
    # image: mariadb
    volumes:
      - mydb:/var/lib/mysql
      # - ./create_mysql.sh:/create_mysql.sh
      # - ./my.cnf:/etc/mysql/my.cnf
      # - ./mydb.sql.gz:/mydb.sql.gz
    environment:
      MARIADB_ROOT_PASSWORD: poi098
      MARIADB_DATABASE: mydb
      MARIADB_USER: mydb
      MARIADB_PASSWORD: abc123
  # pg_db:
  #   image: postgres
  #   volumes:
  #     - pgdb:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: pgdb
  #     POSTGRES_PASSWORD: abc123
  adminer:
    image: adminer
    ports: 
      - 8080:8080

volumes:
  php-dev-context:
  mydb:
  # pgdb: