services:
  php55:
    build:
      # ulimits:
      #   nofile: 10000 # required if you wish to use apt-get
      context: .
      dockerfile: dockerfile.php-dev-55
      # args:
      #   quickform_enabled: 1
    image: php-dev:0.6.3-55
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2223:22"
    expose:
      - 9000
    volumes:
      - php-dev-context:/mnt/context
      # - ./context:/mnt/context
      # - ./php_ini:/mnt/php_ini # to receive original config
      # - ./container_setup.sh:/root/container_setup.sh
      # - ./php55.ini:/usr/local/etc/php/php.ini
      # - ./www:/var/www/html
      # - ./lib:/var/www/lib
    env_file: php_env

  php74:
    build:
      context: .
      dockerfile: dockerfile.php-dev-74
    image: php-dev:0.6.3-74
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2222:22"
    expose:
      - 9000
    volumes:
      - php-dev-context:/mnt/context
      # - ./context:/mnt/context
      # - ./term_keys:/mnt/term_keys
      # - ./php_ini:/mnt/php_ini
      # - ./container_setup.ps1:/root/container_setup.ps1
      # - ./php74.ini:/usr/local/etc/php/php.ini
      # - ./www:/var/www/html
      # - ./lib:/var/www/lib
    env_file: php_env
    stop_grace_period: 1s

  php82:
    build:
      context: .
      dockerfile: dockerfile.php-dev-82
    image: php-dev:0.6.5-82
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "2224:22"
    # networks: # uncomment this section to enable warp proxy
    #   - default
    #   - warp
    expose:
      - 9000
    volumes:
      # - ./php_ini:/mnt/php_ini
      # - ./container_setup.nu:/root/container_setup.nu
      - ./php82.ini:/usr/local/etc/php/php.ini
      # - ./www:/var/www/html
      # - ./lib:/var/www/lib
    env_file: php_env

  nginx55:
    depends_on:
      - php55
    image: docker.io/nginx:1.24-alpine
    ports:
      - 5055:80
    volumes:
      # - ./www:/usr/share/nginx/html
      # - ./js:/usr/share/nginx/html/global
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - PHP_HOST=php55

  nginx74:
    depends_on:
      - php74
    image: docker.io/nginx:1.24-alpine
    ports:
      - 5074:80
    volumes:
      # - ./www:/usr/share/nginx/html
      # - ./js:/usr/share/nginx/html/global
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - PHP_HOST=php74

  nginx82:
    depends_on:
      - php82
    image: docker.io/nginx:1.24-alpine
    ports:
      - 5082:80
    volumes:
      # - ./www:/usr/share/nginx/html
      # - ./js:/usr/share/nginx/html/global
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - PHP_HOST=php82

  my_db:
    build:
      context: .
      dockerfile: dockerfile.mariadb
    image: mydb-dev:0.6.0
    # image: mariadb
    # ports:
    #   - 3306:3306
    # networks: # uncomment this section to enable warp proxy
    #   - default
    #   - warp
    volumes:
      - mydb:/var/lib/mysql
      - ./temp/my_sync_db:/temp/sync_db
      - ./sync_db.sh:/sync_db.sh
      # - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MARIADB_ROOT_PASSWORD: poi098
      MARIADB_DATABASE: mydb
      MARIADB_USER: mydb
      MARIADB_PASSWORD: abc123
      # SYNC_NO_SSL: 1 # uncomment to disable forced SSL connections on sync

  pg_db:
    build:
      context: .
      dockerfile: dockerfile.postgres
    image: pgdb-dev:0.4.0
    # image: postgres:15 # PostgreSQL version: 15.5 (Debian 15.5-1.pgdg120+1) through PHP extension PgSQL
    # ports:
    #   - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
      # - ./pg15-postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - ./pg15-pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./temp/pg_sync_db:/temp/sync_db
      - ./sync_db.sh:/sync_db.sh
    environment:
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: abc123

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  php-dev-context:
  mydb:
  pgdb:
#
# uncomment this section to enable external warp proxy
# networks:
#   warp:
#     name: warp_default
#     external: true
